# This YAML defines the Deployment and Service for the PgBouncer connection pooler.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: yb
  labels:
    app: pgbouncer
spec:
  replicas: 2 # Run multiple replicas for high availability
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
        - name: pgbouncer
          image: pgbouncer/pgbouncer:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: config-volume
              mountPath: /etc/pgbouncer
      volumes:
        - name: config-volume
          configMap:
            name: pgbouncer-config

---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: yb
spec:
  selector:
    app: pgbouncer
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
